/**
 * MineSetu AI — Server-Side RBAC Permission Map
 *
 * Mirrors the frontend permissions from `frontend/src/lib/rbac.ts` but
 * runs on the Vercel serverless API layer. Keeping this as a separate
 * copy avoids cross-workspace TypeScript imports while maintaining the
 * same source of truth (documented in docs/role-permissions.md).
 */

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  // 4 Approved Primary Personas
  ministry_coal: [
    'documents.view',
    'analytics.national',
    'analytics.subsidiary',
    'queries.execute',
    'requests.create',
    'submissions.review',
    'parliamentary.draft',
    'parliamentary.approve',
    'reports.generate',
    'topic.analyze',
    'audit.view',
  ],
  cil_hq: [
    'documents.view',
    'documents.approve',
    'submissions.review',
    'submissions.return',
    'requests.create',
    'requests.respond',
    'analytics.national',
    'analytics.subsidiary',
    'queries.execute',
    'reports.generate',
    'topic.analyze',
    'audit.view',
  ],
  cmpdi: [
    'documents.upload',
    'documents.view',
    'documents.verify',
    'documents.approve',
    'manual.entry',
    'submissions.review',
    'submissions.return',
    'analytics.subsidiary',
    'queries.execute',
    'reports.generate',
    'topic.analyze',
    'audit.view',
  ],
  subsidiary_officer: [
    'documents.upload',
    'documents.view',
    'documents.verify',
    'manual.entry',
    'requests.respond',
    'analytics.subsidiary',
    'queries.execute',
    'audit.view',
  ],

  // Legacy mappings
  ministry_exec: [
    'documents.view',
    'analytics.national',
    'analytics.subsidiary',
    'queries.execute',
    'requests.create',
    'submissions.review',
    'parliamentary.draft',
    'parliamentary.approve',
    'reports.generate',
    'topic.analyze',
    'audit.view',
  ],
  cil_exec: [
    'documents.view',
    'documents.approve',
    'submissions.review',
    'submissions.return',
    'requests.create',
    'requests.respond',
    'analytics.national',
    'analytics.subsidiary',
    'queries.execute',
    'reports.generate',
    'topic.analyze',
    'audit.view',
  ],
  cmpdi_nodal: [
    'documents.upload',
    'documents.view',
    'documents.verify',
    'documents.approve',
    'manual.entry',
    'submissions.review',
    'submissions.return',
    'analytics.subsidiary',
    'queries.execute',
    'reports.generate',
    'topic.analyze',
    'audit.view',
  ],
  subsidiary_mgr: [
    'documents.upload',
    'documents.view',
    'documents.verify',
    'manual.entry',
    'requests.respond',
    'submissions.review',
    'analytics.subsidiary',
    'queries.execute',
    'reports.generate',
    'topic.analyze',
    'audit.view',
  ],
  parliamentary_cell: [
    'documents.view',
    'queries.execute',
    'parliamentary.draft',
    'topic.analyze',
    'reports.generate',
  ],
  field_officer: [
    'documents.upload',
    'documents.view',
    'documents.verify',
    'manual.entry',
    'requests.respond',
    'queries.execute',
  ],
  sys_admin: [
    'documents.upload',
    'documents.view',
    'documents.verify',
    'documents.approve',
    'manual.entry',
    'submissions.review',
    'submissions.return',
    'requests.create',
    'requests.respond',
    'analytics.national',
    'analytics.subsidiary',
    'queries.execute',
    'parliamentary.draft',
    'parliamentary.approve',
    'reports.generate',
    'topic.analyze',
    'admin.users',
    'audit.view',
  ],
};
